#
# Makefile for Chapter 01
#
# Type  make    to compile all the programs
# in the chapter 
#
all: more01 more02

clean:
	rm -f more01 more02


more01: more01.c 
	cc -o more01 more01.c 

more02: more02.c 
	cc -o more02 more02.c 

