#
# Makefile for Chapter 05
#
# Type  make    to compile all the programs
# in the chapter 
#
all: echostate listchars setecho showtty write0

clean:
	rm -f echostate listchars setecho showtty write0


echostate: echostate.c 
	cc -o echostate echostate.c 

listchars: listchars.c 
	cc -o listchars listchars.c 

setecho: setecho.c 
	cc -o setecho setecho.c 

showtty: showtty.c 
	cc -o showtty showtty.c 

write0: write0.c 
	cc -o write0 write0.c 

