#
# Makefile for Chapter 08
#
# Type  make    to compile all the programs
# in the chapter 
#
all: exec1 forkdemo1 forkdemo2 forkdemo3 psh1 psh2 waitdemo1 waitdemo2

clean:
	rm -f exec1 forkdemo1 forkdemo2 forkdemo3 psh1 psh2 waitdemo1 waitdemo2


exec1: exec1.c
	cc -o exec1 exec1.c

forkdemo1: forkdemo1.c
	cc -o forkdemo1 forkdemo1.c

forkdemo2: forkdemo2.c
	cc -o forkdemo2 forkdemo2.c

forkdemo3: forkdemo3.c
	cc -o forkdemo3 forkdemo3.c

psh1: psh1.c
	cc -o psh1 psh1.c

psh2: psh2.c
	cc -o psh2 psh2.c

waitdemo1: waitdemo1.c
	cc -o waitdemo1 waitdemo1.c

waitdemo2: waitdemo2.c
	cc -o waitdemo2 waitdemo2.c

