#
# Makefile for Chapter 11
#
# Type  make    to compile all the programs
# in the chapter 
#
all: popen popen_ex3 popendemo rls rlsd testbdp timeclnt timeserv tinybc

clean:
	rm -f popen popen_ex3 popendemo rls rlsd testbdp timeclnt timeserv tinybc


popen: popen.c
	cc -o popen popen.c

popen_ex3: popen_ex3.c
	cc -o popen_ex3 popen_ex3.c

popendemo: popendemo.c
	cc -o popendemo popendemo.c

rls: rls.c
	cc -o rls rls.c

rlsd: rlsd.c
	cc -o rlsd rlsd.c

testbdp: testbdp.c
	cc -o testbdp testbdp.c

timeclnt: timeclnt.c
	cc -o timeclnt timeclnt.c

timeserv: timeserv.c
	cc -o timeserv timeserv.c

tinybc: tinybc.c
	cc -o tinybc tinybc.c

